name: state_management_cubit
description: "A new Flutter project to learn state management using cubit and bloc."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  bloc: ^8.1.4 #Bloc is the core of the bloc package and contains the main core building blocks like Blocs and Cubits.
  flutter_bloc: ^8.1.6 #Flutter_bloc is a package that contains elements that you will use in building UIs like BlocProvider and BlocBuilder
  equatable: ^2.0.7 #Use equatable for a more convenient way to handle equality in state classes
  logger: ^2.5.0
  freezed: any
  json_annotation: any
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any # Required to use `json_serializable`.
  json_serializable: any
  build_verify: any # Used by tests. Not required to use `json_serializable`.
  flutter_lints: any

flutter:
  uses-material-design: true